version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denden-sparkyfitness_web_1
      APP_PORT: 80

  db:
    image: postgres:15-alpine
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "sparky", "-U", "sparkyuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: sparky
      POSTGRES_USER: sparkyuser
      POSTGRES_PASSWORD: ${APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data

  sparkyfitness-server:
    image: codewithcj/sparkyfitness_server:latest
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3010' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      SPARKY_FITNESS_LOG_LEVEL: INFO
      SPARKY_FITNESS_APP_DB_USER: sparkyuser
      SPARKY_FITNESS_APP_DB_PASSWORD: ${APP_PASSWORD}
      SPARKY_FITNESS_DB_USER: sparkyuser
      SPARKY_FITNESS_DB_PASSWORD: ${APP_PASSWORD}
      SPARKY_FITNESS_DB_HOST: db
      SPARKY_FITNESS_DB_NAME: sparky
      SPARKY_FITNESS_DB_PORT: 5432
      SPARKY_FITNESS_SERVER_PORT: 3010
      NODE_ENV: production
      SPARKY_FITNESS_API_ENCRYPTION_KEY: ${APP_SEED}
      JWT_SECRET: ${APP_SEED}
      SPARKY_FITNESS_FRONTEND_URL: http://${DEVICE_HOSTNAME}:3006
      SPARKY_FITNESS_DISABLE_SIGNUP: false

  web:
    image: codewithcj/sparkyfitness:latest
    restart: on-failure
    depends_on:
      sparkyfitness-server:
        condition: service_healthy
    environment:
      VITE_API_BASE_URL: http://sparkyfitness-server:3010
      API_URL: http://sparkyfitness-server:3010
      SPARKY_FITNESS_API_ENCRYPTION_KEY: ${APP_SEED}
      JWT_SECRET: ${APP_SEED}
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - "3006:80"
