version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    restart: on-failure
    environment:
      APP_HOST: sparkyfitness-web
      APP_PORT: 80
      PROXY_AUTH_ADD_NO_AUTH: "true"
    ports:
      - "3006:80"
    depends_on:
      - sparkyfitness-web

  db:
    image: postgres:15-alpine
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "sparky", "-U", "sparkyuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: sparky
      POSTGRES_USER: sparkyuser
      POSTGRES_PASSWORD: sparkypwd
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data

  sparkyfitness-server:
    image: codewithcj/sparkyfitness_server:latest
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3010' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      SPARKY_FITNESS_LOG_LEVEL: INFO
      SPARKY_FITNESS_APP_DB_USER: sparkyuser
      SPARKY_FITNESS_APP_DB_PASSWORD: sparkypwd
      SPARKY_FITNESS_DB_USER: sparkyuser
      SPARKY_FITNESS_DB_PASSWORD: sparkypwd
      SPARKY_FITNESS_DB_HOST: db
      SPARKY_FITNESS_DB_NAME: sparky
      SPARKY_FITNESS_DB_PORT: 5432
      SPARKY_FITNESS_SERVER_PORT: 3010
      NODE_ENV: production
      SPARKY_FITNESS_API_ENCRYPTION_KEY: ${APP_SEED}
      JWT_SECRET: ${APP_SEED}
      SPARKY_FITNESS_FRONTEND_URL: http://${DEVICE_HOSTNAME}:3006
      SPARKY_FITNESS_DISABLE_SIGNUP: "false"

  sparkyfitness-web:
    image: codewithcj/sparkyfitness:latest
    restart: on-failure
    depends_on:
      sparkyfitness-server:
        condition: service_started
    environment:
      VITE_API_BASE_URL: http://sparkyfitness-server:3010
      API_URL: http://sparkyfitness-server:3010
      SPARKY_FITNESS_API_ENCRYPTION_KEY: ${APP_SEED}
      JWT_SECRET: ${APP_SEED}
